### ISSUE TITLE
Conflict with HTMLEditorField

### ISSUE THREAD

**Issue by simonwinter** [silverstripe/silverstripe-segment-field#23]
**SilverStripe:** 4.2.1

If I have a SegmentField & a HTMLEditorField in a page, the order that the fields are added impacts on whether the Link field on the Editor field works or not.

As an example:

If we include a SlugField like so:

```
$fields->addFieldToTab(
            'Root.Main',
            SegmentField::create('Slug')->setModifiers([...])
                ->setPreview(...)
                ->setDescription(...),
            'Content'
        );
```

Where `Content` is a HTMLEditorField. It results in a javascript error when we attempt to add an external URL:

```
tinymce-cms-590240e062.js:41 Uncaught TypeError: window.jQuery(...).entwine(...).openLinkExternalDialog is not a function
    at p.<anonymous> (tinymce-cms-590240e062.js:41)
    at H.exec.(:8234/admin/pages/edit/EditForm/20/field/ContentBlocks/item/4/anonymous function) (http://localhost:8234/assets/_tinymce/tinymce-cms-590240e062.js:22:27795)
    at Object.p [as execCommand] (tinymce-cms-590240e062.js:22)
    at p.execCommand (tinymce-cms-590240e062.js:26)
    at Object.onclick (tinymce-cms-590240e062.js:41)
    at b.onclick (tinymce-cms-590240e062.js:40)
    at b.e [as fire] (tinymce-cms-590240e062.js:23)
    at b.fire (tinymce-cms-590240e062.js:23)
    at HTMLDivElement.b (tinymce-cms-590240e062.js:23)
    at a (tinymce-cms-590240e062.js:15)
```

However, if we add the Segment Field after the HTMLEditor field, there is no problem.

**Comment by robbieaverill** [comment]
@simonwinter can you please provide your composer.json? Do you think this might have anything to do with the elemental BlockLinkField which uses part of the TinyMCE javascript API?

**Comment by simonwinter** [comment]
Hi @robbieaverill,

We're not using Elemental, so I don't think that'd be an issue.

Here is the composer file - I could be including something dumb here :)

```yaml
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "autoload": {
        "psr-4": {
            "App\\Web\\": "app/src"
        }
    },
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "^4.2.0@stable",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/redirectedurls": "dev-master",
        "silverstripe/googlesitemaps": "dev-master",
        "silverstripe/versioned": "^1.2",
        "symbiote/silverstripe-gridfieldextensions": "^3",
        "silverstripe/segment-field": "dev-master",
        "silverstripe/taxonomy": "^2.0",
        "tractorcow/silverstripe-colorpicker": "^4@dev",
        "heyday/silverstripe-colorpalette": "^2.0",
        "silverstripe/lumberjack": "^2.0",
        "gorriecoe/silverstripe-embed": "^1.0",
        "richardsjoqvist/silverstripe-embedder": "dev-master",
        "littlegiant/silverstripe-seo-editor": "^2.1",
        "innoweb/silverstripe-social-profiles": "dev-master",
        "sheadawson/silverstripe-dependentdropdownfield": "dev-master",
        "salted-herring/salted-cropper": "dev-feature/ss4-upgrade",
        "guzzlehttp/guzzle": "^6.3",
        "gorriecoe/silverstripe-link": "^1.2",
        "gorriecoe/silverstripe-linkfield": "dev-master",
        "phptek/jsontext": "^2.0",
        "undefinedoffset/sortablegridfield": "^2.0",
        "bummzack/sortablefile": "^2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.7",
        "gdmedia/ss-auto-git-ignore": "^1.0",
        "squizlabs/php_codesniffer": "3.*"
    },
    "extra": {
        "project-files-installed": [
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "install-frameworkmissing.html",
            "install.php",
            "web.config"
        ],
        "expose": [
            "themes/default/css",
            "themes/default/img",
            "themes/default/js",
            "themes/default/fonts",
            "themes/default/dist"
        ]
    },
    "scripts": {
        "post-update-cmd": [
            "GDM\\SSAutoGitIgnore\\UpdateScript::Go",
            "composer vendor-expose"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```
